@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Thu Jun 01 11:26:44 +0530 2023
REM SW Build 2700185 on Thu Oct 24 18:46:05 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto eb9ffc732c35418980c74aca1179ea50 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot mux_2_way_3_bit_sim_behav xil_defaultlib.mux_2_way_3_bit_sim -log elaborate.log"
call xelab  -wto eb9ffc732c35418980c74aca1179ea50 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot mux_2_way_3_bit_sim_behav xil_defaultlib.mux_2_way_3_bit_sim -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
